### ISSUE TITLE
[Help] - Clover boot

### ISSUE THREAD

**Issue by tungngodinh** [b166ar/Mac-Mini-Killer#1]
Hello,
I using your EFI folder with  iGPU only. But this do not boot to install mac os. I stuck apple logo.
My system is
- Gigabyte H270-Gaming 3
- Intell core I5 7400
- Kingtom 16Gb 2133
- Samsung evo 840 240Gb
This is my config.plist

[config.txt](https://github.com/b166ar/Mac-Mini-Killer/files/2594981/config.txt)

**Comment by b166ar** [comment]
Hi.
You did not attached problem reporting files. You also has different motherboard, so some settings could be different. For this motherboard you can create a thread on tonymacx86 and mention my nickname there, so I can join discussion.
